[package]
name = "isthisland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shapefile = "0.4.0"
geo-types = "0.7.9"
anyhow = "1"